name: quickresponse
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fontresoft:
    git:
      url: git@github.com:kenresoft/fontresoft.git
      ref: release
  extensionresoft:
    git:
      url: git@github.com:kenresoft/extensionresoft.git
      ref: feature
  bottom_nav:
    git:
      url: git@github.com:kenresoft/bottom_nav.git
      ref: master

  cupertino_icons: ^1.0.5
  go_router: ^10.0.0
  flutter_riverpod: ^2.3.6

  # Location/Map
  geolocator: ^9.0.2
  google_maps_flutter: ^2.4.0
  geocoding: ^2.1.0
  flutter_polyline_points: ^1.0.0 # --- uses a higher version of http
  #open_route_service: ^1.2.3 # --- uses a lower version of http

  # Data
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0

  # File
  path_provider: ^2.1.0
  path: ^1.8.3

  # Media
  carousel_slider: ^4.2.1
  camera: ^0.10.5+3
  image_picker: ^1.0.2
  permission_handler: ^10.4.3
  record: ^4.4.4
  flutter_sound: ^9.2.13


  # Networking
  dio: ^5.3.2
  #flutter_phone_direct_caller: ^2.1.1
  flutter_callkit_incoming:
    path: 'packages/flutter_callkit_incoming'
#  flutter_sms: ^2.3.3
#  sms_advanced:
#    path: 'packages/sms_advanced'
  phone_state: ^1.0.3

  # Firebase
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

