name: quickresponse
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fontresoft:
    git:
      url: git@github.com:kenresoft/fontresoft.git
      ref: master
  extensionresoft:
    git:
      url: git@github.com:kenresoft/extensionresoft.git
      ref: master
  bottom_nav:
    git:
      url: git@github.com:kenresoft/bottom_nav.git
      ref: master

  cupertino_icons: ^1.0.6
  go_router: ^13.0.1
  flutter_riverpod: ^2.4.9
  font_awesome_flutter: ^10.6.0

  # --Location/Map
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  geocoding: ^2.1.1
  flutter_polyline_points: ^2.0.0 # --- uses a higher version of http
  #open_route_service: ^1.2.3 # --- uses a lower version of http

  # --Data/File
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0 #not used anymore verify
  path_provider: ^2.1.2
  path: ^1.8.3
  intl: ^0.18.1
  dio: ^5.3.3 #not used anymore verify

  # Media/Phone
  carousel_slider: ^4.2.1
  camera: ^0.10.5+9
  file_picker: ^6.1.1
  image_picker: ^1.0.7 #not used anymore verify
  flutter_image_compress: ^2.1.0
  cached_network_image: ^3.3.1
  video_player: ^2.8.1
  video_thumbnail: ^0.5.3
  record: ^5.0.1
  just_audio: ^0.9.36
  #flutter_sound: ^9.2.13
  background_sms: ^0.0.4
  #contacts_service: ^0.6.3
  #flutter_ringtone_player: ^4.0.0 #not used anymore verify
  flutter_svg: ^2.0.9
#  flutter_callkit_incoming:
#    path: 'packages/flutter_callkit_incoming'

  # Utilities
  #phone_state: ^1.0.3
  #screen_protector: ^1.3.0
  permission_handler: ^11.1.0
  share_plus: ^7.2.1
  #in_app_update: ^4.2.0
  local_auth: ^2.1.8
  #sensors_plus: ^3.0.3

  # Google
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_analytics: ^10.8.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  in_app_purchase: ^3.1.11

  # Device
  flutter_local_notifications: ^16.1.0
  timezone: ^0.9.2
  flutter_timezone: ^1.0.8
  connectivity_plus: ^5.0.2
  webview_flutter: ^4.4.4
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/data/

