name: quickresponse
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fontresoft:
    git:
      url: git@github.com:kenresoft/fontresoft.git
      ref: release
  extensionresoft:
    git:
      url: git@github.com:kenresoft/extensionresoft.git
      ref: feature
  bottom_nav:
    git:
      url: git@github.com:kenresoft/bottom_nav.git
      ref: master

  cupertino_icons: ^1.0.6
  go_router: ^10.1.2
  flutter_riverpod: ^2.3.6

  # --Location/Map
  geolocator: ^10.0.1
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0
  flutter_polyline_points: ^2.0.0 # --- uses a higher version of http
  #open_route_service: ^1.2.3 # --- uses a lower version of http

  # --Data/File
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.18.1
  dio: ^5.3.2

  # Media/Phone
  carousel_slider: ^4.2.1
  camera: ^0.10.5+4
  file_picker: ^5.5.0
  image_picker: ^1.0.4
  flutter_image_compress: ^2.0.4
  cached_network_image: ^3.2.3
  video_player: ^2.7.2
  video_thumbnail: ^0.5.3
  record: ^4.4.4
  just_audio: ^0.9.35
  #flutter_sound: ^9.2.13
  background_sms: ^0.0.4
  contacts_service: ^0.6.3
  flutter_ringtone_player: ^3.2.0
#  flutter_callkit_incoming:
#    path: 'packages/flutter_callkit_incoming'

  # Utilities
  phone_state: ^1.0.3
  screen_protector: ^1.3.0
  permission_handler: ^10.4.3
  share_plus: ^7.1.0
  #in_app_update: ^4.2.0
  local_auth: ^2.1.7
  sensors_plus: ^3.0.3

  # Google
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_analytics: ^10.5.1
  firebase_storage: ^11.2.8
  cloud_firestore: ^4.9.3
  google_sign_in: ^6.1.5
  in_app_purchase: ^3.1.10

  # Device
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2
  connectivity_plus: ^5.0.0
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/data/

