// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: 'AIzaSyDoUq8ilhxGmPFUhOTin1Gb1O3SseiMRaE',
        appId: '1:659717858737:android:6b37ddd4eea7a2950c4990',
        messagingSenderId: '659717858737',
        projectId: 'quick-response-mobile-app',
        storageBucket: 'quick-response-mobile-app.appspot.com',
      );
      /*throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );*/
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoUq8ilhxGmPFUhOTin1Gb1O3SseiMRaE',
    appId: '1:659717858737:android:6b37ddd4eea7a2950c4990',
    messagingSenderId: '659717858737',
    projectId: 'quick-response-mobile-app',
    storageBucket: 'quick-response-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7YkRFbA_uhutr1k_2qcQlt8idoBAy5RA',
    appId: '1:659717858737:ios:9eb7cc4aebb6bcad0c4990',
    messagingSenderId: '659717858737',
    projectId: 'quick-response-mobile-app',
    storageBucket: 'quick-response-mobile-app.appspot.com',
    androidClientId: '659717858737-kdhd01bndhts9qs8ac6kgmbe0s4t2htr.apps.googleusercontent.com',
    iosClientId: '659717858737-3fqd9od97opv0mleu00dtqa1e6hs9k93.apps.googleusercontent.com',
    iosBundleId: 'com.sharpresponse.quickresponse',
  );
}
